rank and vote count display for all posts
sshh0/mboard pull request #5
Opened 2022-10-21 16:09 UTC by sshh0

user doesn't see his own rank and can't vote for himself

2022-10-21 16:16 UTC, sshh0 commented on mboard/views.py
> +    if created or obj.rank_calc_time < timezone.now() - timedelta(seconds=5):  # session was just created or expired
for now, timedelta just for testing

2022-10-21 16:22 UTC, sshh0 commented on mboard/views.py
> +        thread.vote = Rating.objects.get(user=user, target=thread.session).vote
the thread's OP post isn't picked up by "Thread.post_set.all()" query, so it requires separate handling

2022-10-21 16:46 UTC, ichorid requested changes
Please split the function. Otherwise, seems :+1:

2022-10-22 09:18 UTC, ichorid approved these changes

2022-10-22 09:28 UTC, merged